[project]
name = "fastapi-middleware-instant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "brotli>=1.2.0",
    "fastapi>=0.128.0",
    "orjson>=3.11.5",
    "starlette>=0.50.0",
    "uvicorn>=0.40.0",
]
